### PR TITLE
Fix help message via structopt

### LINKED ISSUE #1: Name displayed in help message is node-cleanup not project-cleanup
Hi there,
thanks for making ```project-cleanup```, I was actually on the cusp of making something similiar but it looks like you did it for me ;). So thanks for that 👍 
When using it I found an artifact of it previous life as ```node-cleanup```

https://github.com/woubuc/project-cleanup/blob/4c39244afea1b47be3dde0376dc42772ba8c2237/src/settings.rs#L9-L11

https://github.com/woubuc/project-cleanup/blob/4c39244afea1b47be3dde0376dc42772ba8c2237/src/settings.rs#L21-L23

You might want to consider using something like [structopt](https://crates.io/crates/structopt) for the argument parsing and validation (which also generates the help messages including version author etc.).

### PR DESCRIPTION
**Pull request by razorheadfx**
Fixes #1.

Structopt generates help messages from crate metadata so it won't be out of sync with the actual crate name and version etc.
Though its no problem if you don't want to pull in another dependency for this.

### CODE REVIEW

**Comment by woubuc** [comment]
Thanks for this PR! Structopt seems very useful and it was on my to-do list to check it out. I just cloned your fork and checked out your changes.

(1) I'm not a big fan of the way structopt orders the help info by default. Can you remove the duplicate display of the name and version, and get it to resemble the order of the current hand-written help text a bit more? I.e.:
1. Description text (what the tool does)
2. Required args (paths)
3. Options / flags
4. Additional info text with links to the repository

(2) I've also added an additional `--ignore` command (pushed the result today) which should be compiled to a Regex, can you make sure that it's also included in the new struct?

(3) As for your fix for the compiler warning on `stdout.flush()`, flushing isn't strictly necessary so `expect`ing may be slightly overkill. I've since solved it in my version by assigning the return value to `_` (see [here](https://github.com/woubuc/project-cleanup/blob/e0c3c2fc654bb645922a51e0a66ee31616b3e48f/src/spinner.rs#L58-L61)). If there's another reason to use `expect` here I don't mind using that, but I don't feel it's necessary to panic if flushing fails.

Once these things are resolved I'll gladly merge this 😃 

I did fix #1 in the hand-written help text as well. But going forward using a library like structopt will make it easier to add options, so I'm not at all opposed to adding the dependency to the project.

**Comment by razorheadfx** [comment]
(1),(2): Already made the changes (i.e. remove the duplicate output, include ignore regex etc) locally and that went without a hitch.
current help output (under windows) would look like this:
```
project-cleanup 0.5.1
Wouter Buckens <wouter@epicteddy.com> (www.woubuc.be)
Clean up build artifacts and dependency directories in Rust, Java and NodeJS projects to free up disk space.

Report bugs and suggestions to https://github.com/woubuc/project-cleanup/issues

USAGE:
    project-cleanup [FLAGS] [OPTIONS] [PATH...]...

FLAGS:
    -a, --all
            Cleanup even recently used projects

    -f, --force
            Skip confirmation prompt

    -h, --help
            Prints help information

    -V, --version
            Prints version information


OPTIONS:
    -i, --ignore <ignore>
            Regex to specify project directories to be ignored


ARGS:
    <PATH...>...
            One or more directories where the project-cleanup should start searching for projects. Defaults to current
            working directory
```
output with `-h` is more compact.
Unfortunately i cannot change the order in which flags/options/args/subcommands are displayed because that is how `clap` does it and `structopt` can only build on top of that.
Another thing that breaks in structopt or the toml parser is the trailing url after your email address in ```Cargo.toml```:
Apparently `:` is converted into `, ` somewhere along the way. Omitting the `https:` may be the way to go there.
```
Wouter Buckens <wouter@epicteddy.com> (https, //www.woubuc.be)
```

(3) I'd rather know if something fails and where it happens - that being said flushing those buffers is not essential as the OS should take care of it once project cleaner exits and the file descriptor gets freed, so not panicking certainly makes more sense from a user perspective.



btw: building in support for colours on windows is (relatively) futile as both powershell and command prompt have problems displaying colours via ANSI escape codes (c.f. [this](https://gist.github.com/XVilka/8346728))
```
Searching for code projects
  [32m✔[0m Searched 74 directories
  [34mi[0m Found 0 projects
Analysing projects
  [32m✔[0m Analysed 0 projects
  [1m0 B[0m of source code and project files
[33mNo projects have directories that can be removed[0m
  This is likely because your projects were recently modified
  Run the application with `[1m--all[0m` to disregard file age
  Try `[1m--help[0m` for more options
```

**Comment by woubuc** [comment]
That help output looks alright to me. Nice work!

If you can remove the panics from `stdout.flush()`, and fix the remaining conflicts, I can merge this one 😃

Wrt the ansi colours on Windows, I just added a fix for that so it should be better in the next version.

**Comment by razorheadfx** [comment]
Rebased in #6

**Pull request closed without merging**
